services:
  serving:
    build:
      context: ./ 
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:latest
    ports:
      - "5000:5000"
    environment:
      - WANDB_API_KEY=
      - WANDB_ENTITY=team08
      - WANDB_PROJECT=IFT6758.2024-B08
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "serving.app:app"]

  streamlit-service:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:latest
    ports:
      - "8501:8501"
    depends_on:
      - serving
    environment:
      - WANDB_API_KEY=
      - WANDB_ENTITY=team08
      - WANDB_PROJECT=IFT6758.2024-B08
      - MODEL_SERVICE_URL=http://serving:5000
    
    
